<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="WebApi\" />
    <None Remove="WebApi\Controllers\" />
    <None Remove="WebApi\Mappings\" />
    <None Remove="Infrastructure\" />
    <None Remove="Infrastructure\ExternalApis\" />
    <None Remove="Infrastructure\Database\" />
    <None Remove="Infrastructure\Database\Mappings\" />
    <None Remove="Infrastructure\Email\" />
    <None Remove="Infrastructure\Email\BackgroundServices\" />
    <None Remove="Infrastructure\Email\Providers\" />
    <None Remove="Infrastructure\Email\Senders\" />
    <None Remove="Core\" />
    <None Remove="Core\Services\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="WebApi\" />
    <Folder Include="WebApi\Controllers\" />
    <Folder Include="WebApi\Mappings\" />
    <Folder Include="Infrastructure\" />
    <Folder Include="Infrastructure\ExternalApis\" />
    <Folder Include="Infrastructure\Database\" />
    <Folder Include="Infrastructure\Database\Mappings\" />
    <Folder Include="Infrastructure\Email\" />
    <Folder Include="Infrastructure\Email\BackgroundServices\" />
    <Folder Include="Infrastructure\Email\Providers\" />
    <Folder Include="Infrastructure\Email\Senders\" />
    <Folder Include="Core\" />
    <Folder Include="Core\Services\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SpaceX.WebApi\SpaceX.WebApi.csproj" />
    <ProjectReference Include="..\..\src\SpaceX.Core.Services.Interfaces\SpaceX.Core.Services.Interfaces.csproj" />
  </ItemGroup>
</Project>
