<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Entities\" />
    <None Remove="Entities\Enums\" />
    <None Remove="Models\" />
    <None Remove="Models\Requests\" />
    <None Remove="Configuration\" />
    <None Remove="Models\Responses\" />
    <None Remove="Models\Authentication\" />
    <None Remove="Models\Email\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Entities\" />
    <Folder Include="Entities\Enums\" />
    <Folder Include="Models\" />
    <Folder Include="Models\Requests\" />
    <Folder Include="Configuration\" />
    <Folder Include="Models\Responses\" />
    <Folder Include="Models\Authentication\" />
    <Folder Include="Models\Email\" />
  </ItemGroup>
</Project>
