<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Models\" />
    <None Remove="Mappings\" />
    <None Remove="Repositories\" />
    <None Remove="Context\" />
    <None Remove="DependencyInjection\" />
    <None Remove="Configuration\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Mappings\" />
    <Folder Include="Repositories\" />
    <Folder Include="Context\" />
    <Folder Include="DependencyInjection\" />
    <Folder Include="Configuration\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpaceX.Core.Domain\SpaceX.Core.Domain.csproj" />
    <ProjectReference Include="..\SpaceX.Infrastructure.Interfaces\SpaceX.Infrastructure.Interfaces.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.27">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
