// <auto-generated />
using System.Diagnostics.CodeAnalysis;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using SpaceX.Infrastructure.Database.Context;

#nullable disable

namespace SpaceX.Infrastructure.Database.Migrations;

[DbContext(typeof(SpaceXDbContext))]
[Migration("20260525180637_AddVerificationTokenToAccount")]
partial class AddVerificationTokenToAccount
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.27")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("SpaceX.Infrastructure.Database.Models.AccountDataModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(45)
                    .HasColumnType("varchar(45)");

                b.Property<bool>("IsVerified")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("VerificationToken")
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Accounts", (string)null);
            });

        modelBuilder.Entity("SpaceX.Infrastructure.Database.Models.PasswordResetTokenDataModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<Guid>("AccountId")
                    .HasColumnType("char(36)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetime(6)");

                b.Property<DateTimeOffset>("ExpiresAtUtc")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("varchar(128)");

                b.HasKey("Id");

                b.HasIndex("AccountId");

                b.ToTable("PasswordResetTokens", (string)null);
            });

        modelBuilder.Entity("SpaceX.Infrastructure.Database.Models.RefreshTokenDataModel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<Guid>("AccountId")
                    .HasColumnType("char(36)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetime(6)");

                b.Property<DateTimeOffset>("ExpiresAtUtc")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("varchar(128)");

                b.HasKey("Id");

                b.HasIndex("AccountId");

                b.ToTable("RefreshTokens", (string)null);
            });

        modelBuilder.Entity("SpaceX.Infrastructure.Database.Models.PasswordResetTokenDataModel", b =>
            {
                b.HasOne("SpaceX.Infrastructure.Database.Models.AccountDataModel", "Account")
                    .WithMany()
                    .HasForeignKey("AccountId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_PasswordResetToken_Account");

                b.Navigation("Account");
            });

        modelBuilder.Entity("SpaceX.Infrastructure.Database.Models.RefreshTokenDataModel", b =>
            {
                b.HasOne("SpaceX.Infrastructure.Database.Models.AccountDataModel", "Account")
                    .WithMany()
                    .HasForeignKey("AccountId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_RefreshToken_Account");

                b.Navigation("Account");
            });
#pragma warning restore 612, 618
    }
}
