<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Database\" />
    <None Remove="Database\Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Database\" />
    <Folder Include="Database\Repositories\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpaceX.Core.Domain\SpaceX.Core.Domain.csproj" />
  </ItemGroup>
</Project>
