<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Accounts\" />
    <None Remove="Helpers\" />
    <None Remove="DependencyInjection\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Accounts\" />
    <Folder Include="Helpers\" />
    <Folder Include="DependencyInjection\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpaceX.Core.Services.Interfaces\SpaceX.Core.Services.Interfaces.csproj" />
    <ProjectReference Include="..\SpaceX.Infrastructure.Interfaces\SpaceX.Infrastructure.Interfaces.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>
</Project>
